(function () {
  const p = (id) => document.getElementById(id);
  let currentProfile = null;
  let posts = [];
  let previewUrl = '';
  let cameraStream = null;
  let mediaRecorder = null;
  let recordedChunks = [];
  let recordedVideoFile = null;
  let feedRefreshTimer = null;

  function esc(value) { return StudentPortal.escapeHtml(value ?? ''); }
  function setStatus(id, message, error = false) { const element = p(id); if (!element) return; element.textContent = message || ''; element.classList.toggle('error', error); }
  function initials(name) { return String(name || 'A').trim().split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase() || 'A'; }
  function formatDate(value) { return new Date(value).toLocaleDateString('pt-BR', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }); }
  function avatar(name, photo, className = 'social-avatar') { const wrap = document.createElement('span'); wrap.className = className; if (photo) { const image = document.createElement('img'); image.src = photo; image.alt = ''; image.loading = 'lazy'; wrap.appendChild(image); } else wrap.textContent = initials(name); return wrap; }

  function renderMedia(container, post) {
    if (!post.media_url) return;
    if (post.media_type === 'video' && window.AcademiaTrainingMedia && /(?:youtube\.com|youtu\.be)/i.test(post.media_url)) { window.AcademiaTrainingMedia.appendVideoPreview(container, post.media_url); return; }
    if (post.media_type === 'image' || /\.(?:jpe?g|png|gif|webp)(?:[?#].*)?$/i.test(post.media_url)) { const image = document.createElement('img'); image.src = post.media_url; image.alt = 'Mídia da publicação'; image.loading = 'lazy'; container.appendChild(image); return; }
    if (post.media_type === 'video' && /^\/uploads\/.*\.(?:mp4|webm|mov)(?:[?#].*)?$/i.test(post.media_url)) { const video = document.createElement('video'); video.src = post.media_url; video.controls = true; video.preload = 'metadata'; container.appendChild(video); return; }
    const link = document.createElement('a'); link.className = 'social-media-link'; link.href = post.media_url; link.target = '_blank'; link.rel = 'noopener noreferrer'; link.textContent = post.media_type === 'video' ? 'Abrir vídeo ou Reels' : 'Abrir conteúdo compartilhado'; container.appendChild(link);
  }

  function renderComments(post, host) {
    const comments = document.createElement('div'); comments.className = 'social-comments';
    (post.comments || []).forEach((comment) => { const row = document.createElement('div'); row.className = 'social-comment'; row.append(avatar(comment.author_name, comment.author_photo)); const body = document.createElement('div'); body.className = 'social-comment-body'; body.innerHTML = `<strong>${esc(comment.author_name)}</strong> ${esc(comment.body)}`; row.appendChild(body); comments.appendChild(row); });
    const form = document.createElement('form'); form.className = 'social-comment-form'; form.innerHTML = '<input type="text" maxlength="800" placeholder="Escreva um comentário..." aria-label="Comentário"><button type="submit">Enviar</button>';
    form.addEventListener('submit', async (event) => { event.preventDefault(); const input = form.querySelector('input'); if (!input.value.trim()) return; const button = form.querySelector('button'); button.disabled = true; try { await StudentPortal.api('/api/student/social/posts/comment', { method: 'POST', body: JSON.stringify({ post_id: post.id, body: input.value.trim() }) }); input.value = ''; await loadFeed(); } catch (error) { setStatus('social-page-status', `Não foi possível comentar: ${error.message}`, true); } finally { button.disabled = false; } });
    host.append(comments, form);
  }

  function renderPost(post) {
    const article = document.createElement('article'); article.className = 'social-post';
    const header = document.createElement('div'); header.className = 'social-post-header';
    const author = document.createElement('button'); author.className = 'social-author'; author.type = 'button'; author.append(avatar(post.author_name, post.author_photo)); const copy = document.createElement('span'); copy.className = 'social-author-copy'; copy.innerHTML = `<strong>${esc(post.author_name)}</strong><small>${esc(formatDate(post.created_at))}</small>`; author.appendChild(copy); author.addEventListener('click', () => openProfile(post.member_id)); header.appendChild(author);
    const menu = document.createElement('small'); menu.textContent = 'Comunidade'; header.appendChild(menu); article.appendChild(header);
    if (post.caption) { const caption = document.createElement('p'); caption.className = 'social-post-caption'; caption.textContent = post.caption; article.appendChild(caption); }
    if (post.media_url) { const media = document.createElement('div'); media.className = 'social-post-media'; renderMedia(media, post); article.appendChild(media); }
    const actions = document.createElement('div'); actions.className = 'social-post-actions';
    const like = document.createElement('button'); like.type = 'button'; like.className = post.viewer_liked ? 'is-liked' : ''; like.textContent = `${post.viewer_liked ? '♥' : '♡'} Curtir ${post.likes_count || 0}`; like.addEventListener('click', async () => { like.disabled = true; try { await StudentPortal.api('/api/student/social/posts/like', { method: 'POST', body: JSON.stringify({ post_id: post.id }) }); await loadFeed(); } catch (error) { setStatus('social-page-status', `Não foi possível curtir: ${error.message}`, true); } finally { like.disabled = false; } });
    const comment = document.createElement('button'); comment.type = 'button'; comment.textContent = `◌ Comentar ${post.comments_count || 0}`; comment.addEventListener('click', () => article.querySelector('.social-comment-form input')?.focus());
    const instagram = document.createElement('button'); instagram.type = 'button'; instagram.textContent = '↗ Instagram'; instagram.addEventListener('click', () => shareInstagram(post));
    actions.append(like, comment, instagram); article.appendChild(actions);
    renderComments(post, article); return article;
  }

  function renderFeed() { const list = p('social-feed-list'); list.replaceChildren(); if (!posts.length) { const empty = document.createElement('div'); empty.className = 'empty-state'; empty.textContent = 'Ainda não há publicações. Seja a primeira pessoa a compartilhar algo.'; list.appendChild(empty); return; } posts.forEach((post) => list.appendChild(renderPost(post))); }

  async function loadFeed() { try { const result = await StudentPortal.api('/api/student/social/feed'); posts = result.posts || []; renderFeed(); } catch (error) { setStatus('social-page-status', `Não foi possível carregar o feed: ${error.message}`, true); } }

  function renderMyProfile(profile, stats) { currentProfile = profile; p('social-my-name').textContent = profile.name || 'Aluno'; p('social-my-bio').textContent = profile.bio || 'Complete seu perfil'; p('social-my-posts').textContent = profile.posts_count || 0; p('social-my-followers').textContent = profile.followers_count || 0; p('social-my-following').textContent = profile.following_count || 0; const avatarHost = p('social-my-avatar'); avatarHost.replaceChildren(); if (profile.profile_photo_url) { const image = document.createElement('img'); image.src = profile.profile_photo_url; image.alt = ''; image.loading = 'lazy'; avatarHost.appendChild(image); } else avatarHost.textContent = initials(profile.name); p('social-my-profile-card').dataset.scheduled = stats?.scheduled_training_count || 0; }

  function personRow(person) { const row = document.createElement('div'); row.className = 'social-person'; row.append(avatar(person.name, person.profile_photo_url)); const info = document.createElement('div'); info.className = 'social-person-info'; info.innerHTML = `<strong>${esc(person.name)}</strong><small>${esc(person.bio || (person.is_private ? 'Perfil privado' : 'Aluno BlueREC'))}</small>`; row.appendChild(info); const view = document.createElement('button'); view.type = 'button'; view.className = 'mini-button secondary'; view.textContent = 'Ver'; view.addEventListener('click', () => openProfile(person.id)); row.appendChild(view); return row; }
  async function loadPeople() { try { const result = await StudentPortal.api(`/api/student/social/people?q=${encodeURIComponent(p('social-people-search').value.trim())}`); const list = p('social-people-list'); list.replaceChildren(); if (!result.people?.length) { const empty = document.createElement('div'); empty.className = 'empty-state'; empty.textContent = 'Nenhum aluno encontrado.'; list.appendChild(empty); return; } result.people.forEach((person) => list.appendChild(personRow(person))); } catch (error) { setStatus('social-page-status', `Não foi possível carregar pessoas: ${error.message}`, true); } }
  async function loadFollowRequests() { try { const result = await StudentPortal.api('/api/student/social/follow-requests'); const requests = result.requests || []; p('social-request-count').textContent = requests.length; p('social-requests-panel').classList.toggle('hidden', !requests.length); const list = p('social-request-list'); list.replaceChildren(); requests.forEach((request) => { const row = document.createElement('div'); row.className = 'social-person'; row.append(avatar(request.name, request.profile_photo_url)); const info = document.createElement('div'); info.className = 'social-person-info'; info.innerHTML = `<strong>${esc(request.name)}</strong><small>Quer seguir você</small>`; row.appendChild(info); const accept = document.createElement('button'); accept.type = 'button'; accept.className = 'mini-button'; accept.textContent = 'Aceitar'; accept.addEventListener('click', () => respondToFollowRequest(request.id, 'accepted')); row.appendChild(accept); const reject = document.createElement('button'); reject.type = 'button'; reject.className = 'mini-button secondary'; reject.textContent = 'Recusar'; reject.addEventListener('click', () => respondToFollowRequest(request.id, 'rejected')); row.appendChild(reject); list.appendChild(row); }); } catch (error) { setStatus('social-page-status', `Não foi possível carregar solicitações: ${error.message}`, true); } }
  async function respondToFollowRequest(requestId, decision) { try { await StudentPortal.api('/api/student/social/follow-request', { method: 'POST', body: JSON.stringify({ request_id: requestId, decision }) }); await loadFollowRequests(); await loadPeople(); } catch (error) { setStatus('social-page-status', `Não foi possível atualizar a solicitação: ${error.message}`, true); } }

  function profileView(profile, stats, posts = [], training = null) {
    const wrap = document.createElement('div'); wrap.className = 'social-profile-view';
    const header = document.createElement('div'); header.className = 'social-profile-view-header'; header.append(avatar(profile.name, profile.profile_photo_url));
    const copy = document.createElement('div'); copy.className = 'social-profile-view-identity'; copy.innerHTML = `<strong>${esc(profile.name)}</strong><small>${profile.is_private ? 'Perfil privado' : 'Perfil público'}</small>`; header.appendChild(copy);
    const actions = document.createElement('div'); actions.className = 'social-profile-view-actions';
    const isMine = String(profile.id) === String(currentProfile?.id);
    if (isMine) { const edit = document.createElement('button'); edit.type = 'button'; edit.className = 'button secondary'; edit.textContent = 'Editar perfil'; edit.addEventListener('click', openEditor); actions.appendChild(edit); }
    else { const follow = document.createElement('button'); follow.type = 'button'; follow.className = 'button'; follow.textContent = profile.viewer_follow_status === 'pending' ? 'Solicitação enviada' : profile.viewer_follows ? 'Deixar de seguir' : 'Seguir'; follow.addEventListener('click', async () => { follow.disabled = true; try { await StudentPortal.api('/api/student/social/follow', { method: 'POST', body: JSON.stringify({ member_id: profile.id }) }); await openProfile(profile.id); await loadPeople(); await loadFeed(); } catch (error) { setStatus('social-page-status', `Não foi possível atualizar o seguimento: ${error.message}`, true); } finally { follow.disabled = false; } }); actions.appendChild(follow); }
    header.appendChild(actions); wrap.appendChild(header);
    const statsEl = document.createElement('div'); statsEl.className = 'social-profile-view-stats'; statsEl.innerHTML = `<span><strong>${esc(profile.posts_count || 0)}</strong><small>posts</small></span><span><strong>${esc(profile.followers_count || 0)}</strong><small>seguidores</small></span><span><strong>${esc(profile.following_count || 0)}</strong><small>a seguir</small></span>`; wrap.appendChild(statsEl);
    if (profile.restricted) { const restricted = document.createElement('div'); restricted.className = 'empty-state'; restricted.textContent = 'Este perfil é privado. Siga para acompanhar as publicações.'; wrap.appendChild(restricted); return wrap; }
    if (profile.bio) { const bio = document.createElement('p'); bio.className = 'social-profile-view-bio'; bio.textContent = profile.bio; wrap.appendChild(bio); }
    if (profile.website_url) { const link = document.createElement('a'); link.href = profile.website_url; link.target = '_blank'; link.rel = 'noopener noreferrer'; link.textContent = profile.website_url; wrap.appendChild(link); }
    const metrics = document.createElement('section'); metrics.className = 'social-profile-view-section'; metrics.innerHTML = '<h4>Estatísticas</h4>'; const metricsGrid = document.createElement('div'); metricsGrid.className = 'social-profile-metrics'; [['Treinos concluídos', stats?.completed_training_count || 0], ['Exercícios planejados', stats?.planned_exercise_count || 0], ['Check-ins', stats?.checkins_count || 0], ['Treinos agendados', stats?.scheduled_training_count || 0]].forEach(([label, value]) => { const item = document.createElement('div'); item.innerHTML = `<strong>${esc(value)}</strong><small>${label}</small>`; metricsGrid.appendChild(item); }); metrics.appendChild(metricsGrid); wrap.appendChild(metrics);
    const workout = document.createElement('section'); workout.className = 'social-profile-view-section'; workout.innerHTML = '<h4>Ficha atual</h4>'; if (training?.plan) { const plan = document.createElement('div'); plan.className = 'social-profile-workout'; plan.innerHTML = `<strong>${esc(training.plan.name)}</strong><small>${esc(training.plan.goal || 'Objetivo não informado')} · ${esc(training.plan.level || 'Nível não informado')}</small><span>${esc(training.exercises?.length || 0)} exercícios planejados</span>`; workout.appendChild(plan); } else { const empty = document.createElement('p'); empty.className = 'empty-state'; empty.textContent = 'Nenhuma ficha atual cadastrada.'; workout.appendChild(empty); } wrap.appendChild(workout);
    const publicationSection = document.createElement('section'); publicationSection.className = 'social-profile-view-section'; publicationSection.innerHTML = '<h4>Publicações</h4>'; const grid = document.createElement('div'); grid.className = 'social-profile-view-posts'; posts.slice(0, 9).forEach((post) => { const tile = document.createElement('div'); tile.className = 'social-profile-post-tile'; if (post.media_url && post.media_type === 'image') { const image = document.createElement('img'); image.src = post.media_url; image.alt = 'Publicação'; image.loading = 'lazy'; tile.appendChild(image); } else if (post.media_url && post.media_type === 'video' && post.media_url.startsWith('/uploads/')) { const video = document.createElement('video'); video.src = post.media_url; video.muted = true; video.controls = true; video.preload = 'metadata'; tile.appendChild(video); } else { tile.textContent = post.caption || 'Publicação'; } grid.appendChild(tile); }); if (grid.children.length) publicationSection.appendChild(grid); else { const empty = document.createElement('p'); empty.className = 'empty-state'; empty.textContent = 'Nenhuma publicação ainda.'; publicationSection.appendChild(empty); } wrap.appendChild(publicationSection); return wrap;
  }

  function openProfile(memberId) { window.location.href = `./student-social-profile.html?member_id=${encodeURIComponent(memberId)}`; }

  async function shareInstagram(post) { const url = post.media_url || window.location.href; try { if (navigator.share) await navigator.share({ title: `Publicação de ${post.author_name}`, text: post.caption || 'BlueREC Academia', url }); else { await navigator.clipboard?.writeText(url); window.open('https://www.instagram.com/', '_blank', 'noopener'); setStatus('social-page-status', 'Link copiado. Cole-o na publicação do Instagram.'); } } catch (error) { if (error.name !== 'AbortError') setStatus('social-page-status', 'Não foi possível compartilhar agora.', true); } }

  async function uploadMedia(file, mediaType) { const imageTypes = ['image/jpeg', 'image/png', 'image/gif', 'image/webp']; const videoTypes = ['video/mp4', 'video/webm', 'video/ogg', 'video/quicktime']; const allowed = mediaType === 'video' ? videoTypes : imageTypes; if (!allowed.includes(file.type)) throw new Error(mediaType === 'video' ? 'Escolha MP4, WebM, OGG ou MOV.' : 'Escolha JPG, PNG, GIF ou WebP.'); const maxBytes = mediaType === 'video' ? 50 * 1024 * 1024 : 5 * 1024 * 1024; if (file.size > maxBytes) throw new Error(mediaType === 'video' ? 'O vídeo não pode ultrapassar 50 MB.' : 'A imagem não pode ultrapassar 5 MB.'); const form = new FormData(); form.append('file', file, file.name); const endpoint = mediaType === 'video' ? '/api/editor/videos' : '/api/editor/images'; const response = await fetch(`${StudentPortal.apiBase}${endpoint}`, { method: 'POST', headers: { Authorization: `Bearer ${StudentPortal.getToken()}` }, body: form }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Não foi possível enviar a mídia.'); return data.location || ''; }

  function stopCameraStream() { if (cameraStream) cameraStream.getTracks().forEach((track) => track.stop()); cameraStream = null; p('social-camera-preview').srcObject = null; }
  function closeCamera() { if (mediaRecorder && mediaRecorder.state !== 'inactive') { mediaRecorder.ondataavailable = null; mediaRecorder.onstop = null; mediaRecorder.stop(); } mediaRecorder = null; recordedChunks = []; stopCameraStream(); p('social-camera-modal').classList.add('hidden'); p('social-camera-preview').classList.remove('hidden'); p('social-camera-empty').classList.remove('hidden'); p('social-camera-start').classList.remove('hidden'); p('social-camera-start').disabled = true; p('social-camera-stop').classList.add('hidden'); p('social-camera-use').classList.add('hidden'); p('social-camera-file-button').classList.remove('hidden'); }
  function supportedRecorderMime() { return ['video/webm;codecs=vp9,opus', 'video/webm;codecs=vp8,opus', 'video/webm', 'video/mp4'].find((type) => window.MediaRecorder?.isTypeSupported?.(type)); }
  async function openCameraRecorder() { p('social-composer-modal').classList.remove('hidden'); p('social-camera-modal').classList.remove('hidden'); p('social-camera-start').disabled = true; p('social-camera-stop').classList.add('hidden'); p('social-camera-use').classList.add('hidden'); p('social-camera-file-button').classList.remove('hidden'); p('social-camera-empty').classList.remove('hidden'); setStatus('social-camera-status', 'Solicitando acesso à câmera...'); stopCameraStream(); if (!window.isSecureContext || !navigator.mediaDevices?.getUserMedia || !window.MediaRecorder) { setStatus('social-camera-status', 'A câmera precisa de HTTPS ou localhost neste navegador. Você pode usar um vídeo salvo.', true); return; } try { cameraStream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } }, audio: true }); const preview = p('social-camera-preview'); preview.srcObject = cameraStream; preview.classList.remove('hidden'); p('social-camera-empty').classList.add('hidden'); p('social-camera-start').disabled = !supportedRecorderMime(); setStatus('social-camera-status', supportedRecorderMime() ? 'Câmera pronta.' : 'Este navegador não permite gravar vídeo neste formato.', !supportedRecorderMime()); } catch (error) { stopCameraStream(); setStatus('social-camera-status', 'Não foi possível acessar a câmera. Verifique a permissão do navegador ou use um vídeo salvo.', true); } }
  function startCameraRecording() { const mimeType = supportedRecorderMime(); if (!cameraStream || !mimeType) return; recordedChunks = []; recordedVideoFile = null; mediaRecorder = new MediaRecorder(cameraStream, { mimeType }); mediaRecorder.ondataavailable = (event) => { if (event.data.size) recordedChunks.push(event.data); }; mediaRecorder.onstop = () => { const blob = new Blob(recordedChunks, { type: mimeType }); const extension = mimeType.includes('mp4') ? 'mp4' : 'webm'; recordedVideoFile = new File([blob], `bluerec-${Date.now()}.${extension}`, { type: blob.type }); p('social-camera-start').classList.add('hidden'); p('social-camera-stop').classList.add('hidden'); p('social-camera-use').classList.remove('hidden'); setStatus('social-camera-status', 'Gravação pronta. Confira e use este vídeo.'); }; mediaRecorder.start(); p('social-camera-start').classList.add('hidden'); p('social-camera-stop').classList.remove('hidden'); setStatus('social-camera-status', 'Gravando...'); }
  function stopCameraRecording() { if (mediaRecorder && mediaRecorder.state !== 'inactive') mediaRecorder.stop(); if (cameraStream) cameraStream.getTracks().forEach((track) => track.stop()); }
  function useRecordedVideo() { if (!recordedVideoFile) return; handleFilePreview(recordedVideoFile, 'video'); closeCamera(); p('social-composer-modal').classList.remove('hidden'); }
  function resetComposer() { closeCamera(); p('social-post-form').reset(); p('social-post-file').value = ''; p('social-post-video-file').value = ''; p('social-post-url').value = ''; p('social-post-url-visible').value = ''; p('social-link-field').classList.add('hidden'); p('social-upload-preview').classList.add('hidden'); p('social-upload-preview-image').hidden = false; p('social-upload-preview-video').hidden = false; p('social-upload-preview-empty').hidden = false; p('social-upload-preview-image').removeAttribute('src'); p('social-upload-preview-video').removeAttribute('src'); p('social-upload-preview-video').load(); recordedVideoFile = null; setStatus('social-post-status', ''); if (previewUrl) URL.revokeObjectURL(previewUrl); previewUrl = ''; }
  function openComposer(mode = 'text') { p('social-composer-modal').classList.remove('hidden'); if (mode === 'photo') { p('social-post-video-file').value = ''; p('social-post-is-video').checked = false; p('social-post-file').click(); } if (mode === 'video') { p('social-post-file').value = ''; p('social-post-is-video').checked = true; openCameraRecorder(); } if (mode === 'link') { p('social-post-is-video').checked = true; p('social-link-field').classList.remove('hidden'); p('social-post-url-visible').focus(); } if (mode === 'text') p('social-post-caption').focus(); }
  function closeComposer() { resetComposer(); p('social-composer-modal').classList.add('hidden'); }
  function syncLinkField() { p('social-post-url').value = p('social-post-url-visible').value.trim(); }

  async function publish(event) { event.preventDefault(); const button = p('social-post-submit'); const photoFile = p('social-post-file').files?.[0]; const videoFile = recordedVideoFile || p('social-post-video-file').files?.[0]; const file = videoFile || photoFile; const fileType = videoFile ? 'video' : photoFile ? 'image' : (p('social-post-is-video').checked ? 'video' : 'image'); try { button.disabled = true; syncLinkField(); setStatus('social-post-status', file ? 'Enviando mídia...' : 'Publicando...'); const mediaUrl = file ? await uploadMedia(file, fileType) : p('social-post-url').value.trim(); await StudentPortal.api('/api/student/social/posts', { method: 'POST', body: JSON.stringify({ caption: p('social-post-caption').value.trim(), media_url: mediaUrl, media_type: file ? fileType : (mediaUrl ? 'video' : 'image') }) }); closeComposer(); setStatus('social-page-status', 'Publicação criada.'); await loadFeed(); } catch (error) { setStatus('social-post-status', `Não foi possível publicar: ${error.message}`, true); } finally { button.disabled = false; } }

  async function openEditor() { try { const result = await StudentPortal.api('/api/student/social/profile'); const profile = result.profile; p('social-profile-name').value = profile.name || ''; p('social-profile-bio').value = profile.bio || ''; p('social-profile-link').value = profile.website_url || ''; p('social-profile-photo-url').value = profile.profile_photo_url || ''; p('social-profile-private').checked = Boolean(profile.is_private); p('social-profile-weight').value = profile.weight_unit || 'kg'; p('social-profile-distance').value = profile.distance_unit || 'km'; p('social-profile-theme').value = profile.theme || 'light'; p('social-profile-language').value = profile.language || 'pt-BR'; p('social-profile-editor-modal').classList.remove('hidden'); } catch (error) { setStatus('social-page-status', `Não foi possível carregar seu perfil: ${error.message}`, true); } }
  async function saveProfile(event) { event.preventDefault(); const button = event.target.querySelector('button[type="submit"]'); try { button.disabled = true; let photo = p('social-profile-photo-url').value.trim(); const file = p('social-profile-photo-file').files?.[0]; if (file) photo = await uploadMedia(file, 'image'); const result = await StudentPortal.api('/api/student/social/profile', { method: 'POST', body: JSON.stringify({ name: p('social-profile-name').value.trim(), bio: p('social-profile-bio').value.trim(), website_url: p('social-profile-link').value.trim(), profile_photo_url: photo, is_private: p('social-profile-private').checked, weight_unit: p('social-profile-weight').value, distance_unit: p('social-profile-distance').value, theme: p('social-profile-theme').value, language: p('social-profile-language').value }) }); p('social-profile-editor-modal').classList.add('hidden'); localStorage.setItem('studentName', result.profile.name); const me = await StudentPortal.api('/api/student/social/profile'); renderMyProfile(me.profile, me.stats); document.querySelectorAll('[data-student-name]').forEach((element) => { element.textContent = result.profile.name; }); } catch (error) { setStatus('social-profile-status', `Não foi possível salvar: ${error.message}`, true); } finally { button.disabled = false; } }

  function csvCell(value) { return `"${String(value ?? '').replaceAll('"', '""')}"`; }
  async function exportData() {
    const button = p('social-export-data');
    try {
      button.disabled = true;
      const [account, social, progress, logs, checkins] = await Promise.all([
        StudentPortal.api('/api/student/profile'),
        StudentPortal.api('/api/student/social/profile'),
        StudentPortal.api('/api/student/progress'),
        StudentPortal.api('/api/student/training/logs'),
        StudentPortal.api('/api/student/checkins?limit=200')
      ]);
      const rows = [
        ['conta', '', account.name, account.email, account.phone],
        ...(social.posts || []).map((post) => ['publicacao', post.created_at, social.profile.name, post.caption || '', post.media_url || '']),
        ...(progress.goals || []).map((goal) => ['meta', goal.target_date, goal.type || '', goal.target_value || '', goal.status || '']),
        ...(progress.assessments || []).map((assessment) => ['avaliacao', assessment.assessment_date, '', assessment.weight_kg || '', assessment.notes || '']),
        ...(logs.data || []).map((log) => ['treino', log.completed_at, log.plan_name || '', log.status || '', log.feedback || '']),
        ...(checkins.data || []).map((checkin) => ['checkin', checkin.checked_at, '', checkin.source || '', checkin.access_status || ''])
      ];
      const csv = ['tipo,data,nome,valor,detalhes', ...rows.map((row) => row.map(csvCell).join(','))].join('\n') + '\n';
      const url = URL.createObjectURL(new Blob(['\ufeff', csv], { type: 'text/csv;charset=utf-8' }));
      const link = document.createElement('a'); link.href = url; link.download = `bluerec-dados-${new Date().toISOString().slice(0, 10)}.csv`; link.click();
      window.setTimeout(() => URL.revokeObjectURL(url), 1000);
      setStatus('social-profile-status', 'Dados exportados em CSV.');
    } catch (error) { setStatus('social-profile-status', `Não foi possível exportar seus dados: ${error.message}`, true); } finally { button.disabled = false; }
  }

  function closeModal(id) { p(id).classList.add('hidden'); }
  async function load() { try { await StudentPortal.init(); const me = await StudentPortal.api('/api/student/social/profile'); renderMyProfile(me.profile, me.stats); await Promise.all([loadFeed(), loadPeople(), loadFollowRequests()]); if (!feedRefreshTimer) feedRefreshTimer = window.setInterval(loadFeed, 120000); } catch (error) { setStatus('social-page-status', `Erro: ${error.message}`, true); } }

  p('social-post-form').addEventListener('submit', publish); p('social-view-profile').addEventListener('click', () => currentProfile?.id && openProfile(currentProfile.id)); p('social-my-avatar').addEventListener('click', () => currentProfile?.id && openProfile(currentProfile.id)); p('social-my-name').addEventListener('click', () => currentProfile?.id && openProfile(currentProfile.id)); p('social-people-search').addEventListener('input', loadPeople); p('social-profile-form').addEventListener('submit', saveProfile); p('social-composer-trigger').addEventListener('click', () => openComposer()); p('social-entry-photo').addEventListener('click', () => openComposer('photo')); p('social-entry-video').addEventListener('click', () => openComposer('video')); p('social-entry-link').addEventListener('click', () => openComposer('link')); p('social-modal-photo').addEventListener('click', () => openComposer('photo')); p('social-modal-video').addEventListener('click', () => openComposer('video')); p('social-modal-link').addEventListener('click', () => openComposer('link')); p('social-composer-close').addEventListener('click', closeComposer); p('social-composer-cancel').addEventListener('click', closeComposer); p('social-post-url-visible').addEventListener('input', syncLinkField); p('social-profile-close').addEventListener('click', () => closeModal('social-profile-modal')); p('social-profile-editor-close').addEventListener('click', () => closeModal('social-profile-editor-modal')); p('social-profile-cancel').addEventListener('click', () => closeModal('social-profile-editor-modal')); [p('social-profile-modal'), p('social-profile-editor-modal'), p('social-composer-modal')].forEach((modal) => modal.addEventListener('click', (event) => { if (event.target === modal) modal.id === 'social-composer-modal' ? closeComposer() : modal.classList.add('hidden'); })); const handleFilePreview = (file, mediaType) => { if (!file) return; if (previewUrl) URL.revokeObjectURL(previewUrl); previewUrl = URL.createObjectURL(file); p('social-upload-preview-image').hidden = mediaType === 'video'; p('social-upload-preview-video').hidden = mediaType !== 'video'; if (mediaType === 'video') { p('social-upload-preview-video').src = previewUrl; p('social-upload-preview-video').load(); } else p('social-upload-preview-image').src = previewUrl; p('social-upload-preview-empty').hidden = true; p('social-upload-preview').classList.remove('hidden'); }; p('social-post-file').addEventListener('change', (event) => handleFilePreview(event.target.files?.[0], 'image')); p('social-post-video-file').addEventListener('change', (event) => handleFilePreview(event.target.files?.[0], 'video'));
  const peopleSearchToggle = p('social-people-search-toggle');
  const peopleSearchWrap = p('social-people-search-wrap');
  peopleSearchToggle?.addEventListener('click', () => {
    const isOpen = peopleSearchWrap.classList.toggle('hidden') === false;
    peopleSearchToggle.setAttribute('aria-expanded', String(isOpen));
    if (isOpen) p('social-people-search')?.focus();
    else {
      p('social-people-search').value = '';
      loadPeople();
    }
  });
  p('social-export-data')?.addEventListener('click', exportData);
  p('social-camera-close').addEventListener('click', closeCamera); p('social-camera-cancel').addEventListener('click', closeCamera); p('social-camera-start').addEventListener('click', startCameraRecording); p('social-camera-stop').addEventListener('click', stopCameraRecording); p('social-camera-use').addEventListener('click', useRecordedVideo); p('social-camera-file-button').addEventListener('click', () => p('social-camera-file').click()); p('social-camera-file').addEventListener('change', (event) => { const file = event.target.files?.[0]; if (!file) return; recordedVideoFile = file; handleFilePreview(file, 'video'); closeCamera(); p('social-composer-modal').classList.remove('hidden'); }); p('social-camera-modal').addEventListener('click', (event) => { if (event.target === event.currentTarget) closeCamera(); });
  document.addEventListener('keydown', (event) => { if (event.key === 'Escape') { if (!p('social-camera-modal').classList.contains('hidden')) closeCamera(); if (!p('social-composer-modal').classList.contains('hidden')) closeComposer(); document.querySelectorAll('.modal:not(.hidden)').forEach((modal) => { if (!['social-composer-modal', 'social-camera-modal'].includes(modal.id)) modal.classList.add('hidden'); }); } });
  load();
}());
