ALTER TABLE members ADD COLUMN IF NOT EXISTS cpf VARCHAR(11);
ALTER TABLE members ADD COLUMN IF NOT EXISTS rg VARCHAR(30);
ALTER TABLE members ADD COLUMN IF NOT EXISTS phone_country_code VARCHAR(8) DEFAULT '+55';
ALTER TABLE members ADD COLUMN IF NOT EXISTS emergency_contact_name VARCHAR(160);
ALTER TABLE members ADD COLUMN IF NOT EXISTS emergency_contact_phone VARCHAR(32);
ALTER TABLE members ADD COLUMN IF NOT EXISTS postal_code VARCHAR(12);
ALTER TABLE members ADD COLUMN IF NOT EXISTS street VARCHAR(220);
ALTER TABLE members ADD COLUMN IF NOT EXISTS address_number VARCHAR(30);
ALTER TABLE members ADD COLUMN IF NOT EXISTS address_complement VARCHAR(160);
ALTER TABLE members ADD COLUMN IF NOT EXISTS neighborhood VARCHAR(160);
ALTER TABLE members ADD COLUMN IF NOT EXISTS city VARCHAR(160);
ALTER TABLE members ADD COLUMN IF NOT EXISTS state VARCHAR(80);
ALTER TABLE members ADD COLUMN IF NOT EXISTS country VARCHAR(100) DEFAULT 'Brasil';

CREATE UNIQUE INDEX IF NOT EXISTS members_gym_cpf_unique
  ON members (gym_id, cpf)
  WHERE cpf IS NOT NULL AND cpf <> '';

CREATE INDEX IF NOT EXISTS members_gym_rg_idx ON members (gym_id, rg);
CREATE INDEX IF NOT EXISTS members_gym_city_idx ON members (gym_id, city);
